[package]
name = "fractal"
version = "0.1.0"
authors = ["Anders Musikka <anders@andersmusikka.se>"]

[dependencies]
serde="1.0.28"
serde_derive="1.0.28"
savefile-derive= { path = "savefile-derive" }


